jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: common/build.yml
  - template: common/lint.yml
  - template: common/test.yml
  - task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
    displayName: 'VS IntelliNav Upload'
    inputs:
      vsckEndpoint: 'vscloudkernel-dev' # name of the IntelliNav service connection
      nugetpat: 'vscloudkernel-nuget' # name of the NuGet service connection
      language: 'typescript' # languages in your repo, separated by commas
      githubpat: 'vsls-contrib' # if your repo is on GitHub, this is the name of the GitHub service connection (GitHub organization by default)

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: common/build.yml
  - template: common/publish-vsix.yml # Only publish vsix from linux build since we use this to release and want to stay consistent
  - template: common/lint.yml
  - template: common/test.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
  - template: common/build.yml
  - template: common/lint.yml
  - template: common/test.yml
